#!/bin/env bash

OPERATION="$1"

INSTALL_DIR="${VPN_INSTALL_DIR:-$HOME/.vpn}"

SUCCCESS="$(gum style --bold --foreground='#198754')"
INFO="$(gum style --bold --foreground='#0dcaf0')"
WARN=$(gum style --bold --foreground='#ffc107')
ERROR="$(gum style --bold --foreground='#dc3545')"

check_dependencies() {
  if ! which gum &>/dev/null; then
    curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg >/dev/null
    echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list >/dev/null
    sudo apt update && sudo apt install gum -y >/dev/null
  fi

  if ! which f5fpc &>/dev/null; then
    gum style --bold --foreground='#dc3545' "F5 Linux CLI is not installed"
    gum spin --spinner dot --title "Installing..." -- curl https://iconnect.global.volvocars.biz/public/share/linux_f5cli.x86_64.deb --output /tmp/linux_f5cli.x86_64.deb && sudo dpkg -i /tmp/linux_f5cli.x86_64.deb >/dev/null && gum style --bold --foreground='#198754' "F5 Linux CLI successfully installed"
  fi

  if ! which java &>/dev/null; then
    gum style --bold --foreground='#dc3545' "Java Runtime Environment is not installed"
    gum spin --spinner dot --title "Installing..." -- sudo apt update && sudo apt install openjdk-11-jre -y >/dev/null && gum style --bold --foreground='#198754' "Java Runtime Environment successfully installed"
  fi

  if [[ ! -f "$HOME/.pointsharp/pointsharp_v2.jar" ]]; then
    gum style --bold --foreground='#dc3545' "Pointsharp CLI is not installed"
    mkdir "$HOME/.pointsharp/"
    gum spin --spinner dot --title "Installing..." -- curl https://confluence.volvocars.biz/download/attachments/259652341/pointsharp_v2.jar --output "$HOME/.pointsharp/pointsharp_v2.jar" >/dev/null && gum style --bold --foreground='#198754' "Pointsharp CLI successfully installed"
  fi
}

check_dependencies

menu() {
  OPERATION=$(gum choose --header "Select an operation" "connect" "disconnect" "status" "credentials" "reconfigure" "install" "uninstall" "exit")
  main
}

check_installation() {
  if [[ ! -f "$INSTALL_DIR/vpn" ]]; then
    gum confirm "VPN utility is not installed in your system. Would you like to install?" && install
  fi
}

set_credentials() {
  if [[ ! -d "$INSTALL_DIR" ]]; then
    mkdir "$INSTALL_DIR"
  fi

  if [[ ! -f "$INSTALL_DIR/pwd" ]]; then
    touch "$INSTALL_DIR/pwd"
  else
    sudo chmod 644 "$INSTALL_DIR/pwd"
    sudo chown "$USER":"$USER" "$INSTALL_DIR/pwd"
  fi

  gum input --password --placeholder "Enter your password (same as CDSID)" >"$INSTALL_DIR/pwd"
  gum input --password --placeholder "Enter your PointSharp 4 digits PIN" >>"$INSTALL_DIR/pwd"
  gum input --password --placeholder "Enter your PointSharp 6 digits OTP" >>"$INSTALL_DIR/pwd"
  chmod 400 "$INSTALL_DIR/pwd"
  sudo chown root:root "$INSTALL_DIR/pwd"
}

install() {
  if [[ -f "$INSTALL_DIR/vpn" ]]; then
    gum style --bold --foreground='#ffc107' "VPN utility is already installed in your system"
    menu
  fi

  set_credentials

  cp "$0" "$INSTALL_DIR/vpn"
  chmod +x "$INSTALL_DIR/vpn"
  sudo ln -f "$INSTALL_DIR/vpn" "/usr/local/bin/vpn"

  if which vpn >/dev/null; then
    gum style --bold --foreground='#198754' "VPN utility successfully installed in '$(which vpn)'"
    menu
  else
    gum style --bold --foreground='#dc3545' "Installation failed"
  fi
}

uninstall() {
  if [[ -f "/usr/local/bin/vpn" ]]; then
    sudo rm "/usr/local/bin/vpn"
    gum style --bold --foreground='#198754' "VPN utility successfully uninstalled"
  fi
}

check_installation

main() {
  while true; do
    case "${OPERATION}" in
    "connect")
      WIFI_NAME=('VolvoCars.1x' 'VolvoCars')

      for network in "${WIFI_NAME[@]}"; do
        if iwgetid | grep "$network" >/dev/null; then
          gum style --bold --foreground='#ffc107' "Connected to '${network}' network that does not require VPN"
          exit 0
        fi
      done

      f5fpc --info >/dev/null
      if [[ "$?" == "5" ]]; then
        gum style --bold "$(f5fpc --stop)"
      fi

      SERVER_ADDR="https://iconnect.global.volvocars.biz"
      PASSWORD="$(sudo sed -n '1p' $INSTALL_DIR/pwd)" && echo "Credentials loaded"
      PIN="$(sudo sed -n '2p' $INSTALL_DIR/pwd)"
      OTP="$(sudo sed -n '3p' $INSTALL_DIR/pwd)"
      UNAME="$USER"
      POINTSHARP_TOKEN="$(java -jar $HOME/.pointsharp/pointsharp_v2.jar ${OTP})"

      f5fpc --start -u "${UNAME}" -p "${PIN}${POINTSHARP_TOKEN}${PASSWORD}" -t "${SERVER_ADDR}" >/dev/null
      gum spin --spinner points --title "Connecting" -- sleep 20
      gum style --bold "$(f5fpc --info | head -1)"

      exit
      ;;

    "disconnect")
      gum spin --spinner points --title "Disconnecting" -- f5fpc --stop
      exit
      ;;

    "status")
      gum style --bold "$(f5fpc --info | head -1)"
      exit
      ;;

    "install")
      install
      exit
      ;;

    "uninstall")
      uninstall
      exit
      ;;

    "credentials")
      sudo gum pager <"${INSTALL_DIR}/pwd"
      exit
      ;;

    "reconfigure")
      set_credentials
      exit
      ;;

    "exit")
      exit 0
      ;;

    *)
      if [[ -z "${OPERATION}" ]]; then
        menu
      else
        gum style --bold --foreground='#dc3545' "Unrecognized option '${OPERATION}'"
        menu
      fi
      ;;
    esac
  done
}

main
